### ISSUE TITLE
Hooks can only be called inside the body of a function component

### ISSUE THREAD

**Issue by zisheng-ai** [rhdeck/react-native-screenshot-notifier#1]

**Comment by rhdeck** [comment]
True! But not sure what makes that an issue. Glad to help if you share more data, closing for now.

**Comment by zisheng-ai** [comment]
this is my lib that base yours：https://github.com/sishuguojixuefu/react-native-screenshot

**Comment by zisheng-ai** [comment]
I think addListener is good practice，not useScreenshotNotifier()
